apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    app: web
    project: roboshop
    tier: web
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
